- jinja2 Mark Up has been deprecated resulting in ImportError: cannot import name 'Markup' from 'jinja2.utils'. Replaced with import of MarkUp from markupsafe